postgres:
    image: projectfifo/metric_metadata
    ports:
        - "5432:5432"

db:
    image: projectfifo/ddb
    ports:
        - "5555:5555"

fe:
    image: projectfifo/dfe
    environment:
        - DB_NODE=db.local
        - PG_NODE=postgres.local
    ports:
        - 8070:8080
    links:
        - db:db.local
        - postgres:postgres.local

proxy:
    image: projectfifo/ddb_proxy
    environment:
        - DB_NODE=db.local
        - PG_NODE=postgres.local
    ports:
        - 2003:2003
        - 8086:8086
        - 4242:4242
        - 9999:9999
        - 1234:1234
    links:
        - db:db.local
        - postgres:postgres.local

statsd:
    image: jaconel/statsd
    environment:
        - GRAPHITE_PORT_2003_TCP_PORT=2003
        - GRAPHITE_PORT_2003_TCP_ADDR=proxy.local
        # - GRAPHITE_GLOBAL_PREFIX
        # - GRAPHITE_LEGACY_NAMESPACE
        - STATSD_PORT=8125
        # - STATSD_DUMP_MSG
        # - STATSD_DEBUG
        - STATSD_FLUSH_INTERVAL=1000
        - PROXY_HOST=proxy.local
    ports:
        - 8125:8125
        - 8125:8125/udp
        - 8126:8126
    links:
        - proxy:proxy.local

grafana:
    image: grafana/grafana
    environment:
        - GF_INSTALL_PLUGINS=dalmatinerdb-datasource
    ports:
        - 3000:3000
    links:
        - fe:fe.local

#broker:
#    image: vromero/activemq-artemis:1.5.4
#    ports:
#      - "61616:61616"
#      - "8161:8161"
#      - "5672:5672"
#    environment:
#      - ARTEMIS_USERNAME=guest
#      - ARTEMIS_PASSWORD=guest
#      - ARTEMIS_MIN_MEMORY=512M
#      - ARTEMIS_MAX_MEMORY=1024M
#      - ARTEMIS_PERF_JOURNAL=AUTO

#groot:
#    build: .
#    dockerfile: Dockerfile
#    environment:
#      - BROKER_CONN=tcp://broker.local:61616?blockOnDurableSend=false&consumerWindowSize=0&protocols=Core
#    ports:
#      - 8090:8090
#    links:
#      - broker:broker.local
